daemon:
    name: Production Cluster

general:
    eventlogger: [$eventLoggerIp]
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    bind: 0.0.0.0:[@astronIp]

uberdogs:
    - class: ClientServicesManager
      id: 1000
      anonymous: true

    - class: DistributedTravelAgent
      id: 1001
      anonymous: false

    - class: PiratesFriendsManager
      id: 1002
      anonymous: false
    
    - class: DistributedCrewMatchManager
      id: 1003
      anonymous: false

    - class: DistributedMatchMaker
      id: 1004
      anonymous: false

    - class: GuildManager
      id: 1005
      anonymous: false

roles:
    - type: stateserver
      control: [$stateServer]

    - type: database
      control: 1101
      generate:
          min: 100000000
          max: 399999999
      backend:
        type: mongodb
        server: [$mongoIp]

    - type: dbss
      database: 1101
      ranges:
          - min: 100000000
          - max: 399999999

    - type: eventlogger
      bind: 0.0.0.0:[@eventLoggerIp]
      output: ../logs/events-%y%m%d_%H%M%S.log
